name: Calculate CO2
on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate CO2
        uses: GeopJr/CO2@v1
        with:
          url: "https://geopjr.dev/"
          renewable: true

- name: Save state
  run: echo "{name}={value}" >> $GITHUB_STATE

- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT